name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis (SonarCloud)
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 16
      - run: |
          npm ci
          npm run build
          xvfb-run --auto-servernum npm test
